### ISSUE TITLE
AttributeError: module 'snntorch' has no attribute 'Convolution'

### ISSUE THREAD

**Issue by Luchen-077** [ECNU-Cross-Innovation-Lab/Mamba-Spike#1]
Traceback (most recent call last):
  File "C:\LuChen\Mamba-Spike\Mamba-Spike-main\main.py", line 34, in <module>
    main()
  File "C:\LuChen\Mamba-Spike\Mamba-Spike-main\main.py", line 17, in main
    model = MambaSpike(input_size, hidden_size, output_size, num_layers)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\LuChen\Mamba-Spike\Mamba-Spike-main\model.py", line 40, in __init__
    self.spiking_conv = SpikingConv2d(in_channels=1, out_channels=16, kernel_size=3, stride=1, padding=1)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\LuChen\Mamba-Spike\Mamba-Spike-main\layers.py", line 36, in __init__
    self.conv = snn.Convolution(self.in_channels, self.out_channels, self.kernel_size, self.stride, self.padding, self.dilation, self.groups, self.bias, self.spike_grad)
                ^^^^^^^^^^^^^^^
AttributeError: module 'snntorch' has no attribute 'Convolution'

python 3.11.9
torch 2.3.0
snntorch 0.9.1
spikingjelly 0.0.0.0.14

**Comment by li-25-creater** [comment]
我也遇到了这个问题，我尝试用nn.Conv2d和snn.Leaky两层来代替这里出错的部分，但引起后续维度等的问题，请问您后面有解决这个问题吗？

**Comment by IceIce1ce** [comment]
+1

**Comment by D-ST-Sword** [comment]
The detailed user guide has been updated
